### ISSUE TITLE
only scrobble when clicking the button

### ISSUE THREAD

**Issue by juliabla** [web-scrobbler/web-scrobbler#1560]
Thanks a lot for the Last.fm web scrobbler btw!

It would be cool though, to only scrobble when clicking the button, instead of just everything from specific websites.

### Expected behavior
1. Select no website to be scrobbled from automatically
2. Listen to a song
3. Click the scrobbler button to scrobble only that song

### Current behavior
1. Select websites to automatically scrobble from
2. Listen to a song on website X
3. Song will be automatically scrobbled just as every song played on website X

### Possible solution
click-to-scrobble

### Context
I don't want every single song I listen to on one or more different kind of platforms to show up in my Last.fm history. If I'm listening to music from my iPod, the music is on there because I like it. On the internet though, I sometimes listen to songs that I just stumbled upon, just want to check them out, not necessarily because I like them and want them in my history.

**Comment by inverse** [comment]
You can disable the scrobbler for all sites and only enable it when you want it on. 

Not sure that's exactly what you want though.

**Comment by juliabla** [comment]
No, because to enable it, I would have to go into the add-on settings and select that website. And then it would scrobble everything from that website again.

**Comment by alexesprit** [comment]
I'd add an option to turn on manual scrobbling. If this option is turned on, the extension won't scrobble tracks. If an user wants to scrobble a track, they should click on "Scrobble" button in the popup window:
![image](https://user-images.githubusercontent.com/1119267/59565444-593be800-905c-11e9-9499-7c82cb5adac4.png)

This option will be turned off by default.

Any other features (now playing notifications, track recognition) will be unchanged.

The only thing I have no idea how to notify if manual mode is turned on. Any ideas how to resolve this?

**Comment by alexesprit** [comment]
Also, I have some question regarding this issue. Let's imagine a situation.
1. The manual mode is turned on.
2. User plays a track A.
3. Track A is not scrobbled due to manual mode enabled.
4. Track A ends, and track B starts to play.

What should we do with track A? Should we lose this potential scrobble, or should we save it to some internal cache to allow a user to edit/submit scrobble later?

**Comment by kini** [comment]
IMO the first option (lose the potential scrobble) can be implemented to start with; if #291 is implemented, then this manual mode can plug into that by adding not only unrecognized, but also unapproved, tracks into the queue.

**Comment by alexesprit** [comment]
> then this manual mode can plug into that by adding not only unrecognized, but also unapproved, tracks into the queue.

Yes, I was thinking in the same way, as the unified storage is easier to use.

**Comment by kini** [comment]
Also,

>Any other features (now playing notifications, track recognition) will be unchanged.
>
>The only thing I have no idea how to notify if manual mode is turned on. Any ideas how to resolve this?

Maybe delay the "now playing" notification until the user approves the scrobble? That way the user will notice that there is no notification even though music is playing, and will go and check the tab and see that manual mode is turned on.

**Comment by alexesprit** [comment]
This won't work if notifications are turned off.

**Comment by kini** [comment]
Good point. Then, what about changing the icon in the toolbar? Maybe the [page_action_skipped](https://github.com/web-scrobbler/web-scrobbler/blob/master/src/icons/page_action_skipped.svg) icon can also be used for "unapproved", because similar to "skipped", it is a state that means the currently playing song will not be scrobbled.

**Comment by kini** [comment]
Ping. Is there anything I can help with on this issue?

**Comment by alexesprit** [comment]
> Good point. Then, what about changing the icon in the toolbar? Maybe the page_action_skipped icon can also be used for "unapproved", because similar to "skipped", it is a state that means the currently playing song will not be scrobbled.

We now have an ability to skip songs manually, and the extension skips podasts if it's allowed. I have an idea to "unskip" songs.

I think we can go with way, when a manual scrobbling will skip all songs by default, and you can "unskip" them to scrobble.

**Comment by 06000208** [comment]
I would really appreciate this feature, primarily for youtube, because youtube isn't only music. I'd be willing to help make this happen.

If anyone else is needing a workaround, for now you can enable/disable the connector for a specific site via the extensions's context menu.

> I think we can go with way, when a manual scrobbling will skip all songs by default, and you can "unskip" them to scrobble.

As long as unskipping could be done by left clicking the extension's [browser_action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action) or [page_action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action), and all songs is configurable per site, I believe this is a suitable implementation 👍

Though as far as user interaction/design goes, rather than displaying the song as skipped and you'd unskip to scrobble, it could be represented as "Scrobble Track" or "Add Scrobble". Not it matters too much with a button.

**Comment by bs** [comment]
I'm a big fan of a `click-to-scrobble` button on a currently playing track or #291. I often listen to something on an unsupported platform (iOS, Safari on Mac, etc) and want to load up the page and just insta-scrobble. (I often do this from [Marvis](https://apps.apple.com/us/app/marvis-pro/id1447768809) if the song is on Apple Music, for example, but am out of luck if elsewhere.)

**Comment by yayuyokitano** [comment]
Update on this: We now have a setting that allows users to set to "Only scrobble edited tracks". #3222 
This means that in order to scrobble a track, the user MUST go in and verify the metadata, then click edit, and it will scrobble.
After this, the same track will always scrobble automatically, but other tracks on the same site will not.
Is this sufficient to close this issue?

**Comment by kini** [comment]
Sounds good to me! (Though I didn't open the ticket.) Thanks!

**Comment by PiotrDabrowskey** [comment]
Sound good to me as well! There'll be two clicks needed but it's totally fine :+1: I'm not an OP thought too

Thanks for the information! I've just set "Scrobble edited tracks only" for the platform, where I needed this option.

**Comment by yayuyokitano** [comment]
Since I have not heard any complaints, I will close this.
