### ISSUE TITLE
Spotify web player ads scrobbled

### ISSUE THREAD

**Issue by Chipmunkey** [web-scrobbler/web-scrobbler#1599]
After 10-15 minutes of music, the first ad usually plays and the Chrome plugin sees it as a song. If I get to it soon enough, I can just tell it to skip, otherwise, I have to hunt them down later in my Last.fm feed and delete them.

**Comment by inverse** [comment]
@Chipmunkey is this still an issue? There was a fix shortly before you posted this that should have resolved this?

**Comment by Chipmunkey** [comment]
Yeah. It's still happening for me. I used it earlier today and it scrobbled
some ads.

**Comment by alexesprit** [comment]
What are an artist name and a track title when ads are scrobbling?

**Comment by Chipmunkey** [comment]
This is how the ads are showing up on my Last.fm timeline:

StateFarm - StateFarm (no space between the words)
The Home Depot - The Home Depot
Der KFC - Find a KFC
Indeed - INDEED
Wendy's - Wendy's

**Comment by Chipmunkey** [comment]
I've been skipping them when I can or deleting them but I'll leave them on here for a while if you need to check:
https://www.last.fm/user/MunkeyChips

**Comment by Chipmunkey** [comment]
And there was just an ad for Act mouthwash. It showed up like:
Act - Act

**Comment by inverse** [comment]
Interesting. I wonder if there is anything in the DOM that shows it's an advert.

**Comment by SeijiSuenaga** [comment]
I've been experiencing this as well, in Firefox and Chrome.

**Comment by Pendrokar** [comment]
Tried re-enabling extension, other than causing duplicates along with official scrobbler #1621, this also occured with the following scrobbling info:
Spotify - Spotify

**Comment by SeijiSuenaga** [comment]
I tried fixing this by removing the following from the connector's `isMusicPlaying()` function:

```javascript
if (Connector.getArtist() !== 'Spotify') {
	return true;
}
```

But it's still a bit broken. When an ad started playing, `isScrobblingAllowed()` returned false, which triggered `resetState()`, but the Web Scrobbler menu still showed the ad as the current track. I haven't yet found how to clear that.

Then, because the ad was the current track, and `onStateChanged()` was returning early without handling state changes:
- When I paused the ad, `isPlaying` stayed true, and the ad was scrobbled even while paused.
- When I unpaused the ad and a couple more ads played afterward, Web Scrobbler still showed the first ad as the current track.  Those other ads weren't scrobbled, at least.

**Comment by SeijiSuenaga** [comment]
This bug has returned. Commit fdbbc9703555d07798b421fbd82f56a3cd8bbe41 expects ad URLs containing `shrt.spotify.com`, but here's an example of the ad URLs I'm seeing: 
`https://ad.doubleclick.net/ddm/trackclk/N884051.143769SPOTIFYUSAINC/B23530725.260494019;dc_trk_aid=456486803;dc_trk_cid=124878211;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=`

**Comment by alexesprit** [comment]
@SeijiSuenaga thanks for reporting! I added this URL to the black list.

**Comment by inverse** [comment]
@alexesprit you're on fire :fire:
