### ISSUE TITLE
doesn't scrobble full stop (unsupported site on everything)

### ISSUE THREAD

**Issue by teletrail** [web-scrobbler/web-scrobbler#1632]
as said above, tried using stable and trunk.

plugin works in chrome-unstable.

logged in fine, just refuses to recognise any site as scrobble-able.

happens across two different installs.

any help would be good, thanks.

**Comment by keemyb** [comment]
Just a suggestion, are you using an adblocker?

**Comment by teletrail** [comment]
yes, I'm using 9ne.

**Comment by inverse** [comment]
Are you able to get any logs? 
https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by teletrail** [comment]
some error about youtube.js?

it half-works on bandcamp, but not consistently.



> rror: WebExtension context not found!
> ExtensionParent.jsm:1009:13
> Error: Could not establish connection. Receiving end does not exist.
> background.js:1:417
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Sending message that cannot be cloned. Are you trying to send an XPCOM
> object? ExtensionUtils.jsm:546:50
> uncaught exception: undefined
> TypeError: window is null WebRequestContent.js:124:7
> Attempt to set a forbidden header was denied: Connection
> 4171528715-lcs_client_bin.js:194:386
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Error: Could not establish connection. Receiving end does not exist.
> background.js:1:417
> TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an
> object.[Learn More]
> ExtensionContent.jsm:489:18
> An iframe which has both allow-scripts and allow-same-origin for its
> sandbox attribute can remove its sandboxing.
> hollowfeeling
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Security Error: Content at
> moz-extension://d4407264-545f-41f9-92f9-d94798a6565e/ may not load data
> from blob:null/9d1bf55e-8db7-4eb4-8601-0041d08ded1d.
> response is undefined include.preload.js:750
> [Show/hide message details.] Unchecked lastError value: Error: sender.page
> is undefined include.preload.js:744
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> [Show/hide message details.] Promise rejected after context unloaded:
> Promised response from onMessage listener went out of scope
> content_script_bundle.js:1
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> Security Error: Content at
> moz-extension://d4407264-545f-41f9-92f9-d94798a6565e/ may not load data
> from blob:null/96751d8f-c6e0-413d-8221-50ae8f3261d4.
> [Show/hide message details.] sender.page is undefined
> MessageChannel.jsm:964
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> Loaded for the first time, injecting the scripts inject.js:37:5
> Injecting vendor/jquery.min.js inject.js:61:7
> [Show/hide message details.] Unchecked lastError value: Error: Could not
> establish connection. Receiving end does not exist. inject.js:30
> Injecting core/content/reactor.js inject.js:61:7
> Injecting core/content/filter.js inject.js:61:7
> Injecting core/content/util.js inject.js:61:7
> Injecting core/content/connector.js inject.js:61:7
> Injecting connectors/soundcloud.js inject.js:61:7
> Injecting core/content/starter.js inject.js:61:7
> Tab 67: Created controller for SoundCloud connector controller.js:588:6
> Subsequent ajax navigation, the scripts are already injected
> inject.js:32:6
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
> remote resource at
> https://api-v2.soundcloud.com/promoted/users?device_locale=en&client_id=3Goi9X5NOF7g1ofGbmYEkpveejwvlqjd&app_version=1526649907&app_locale=en.
> (Reason: CORS request did not succeed).
> Security Error: Content at
> moz-extension://d4407264-545f-41f9-92f9-d94798a6565e/ may not load data
> from blob:null/bd06966b-6c72-4d04-b0f0-dd46054afcd7.
> [Show/hide message details.] sender.page is undefined
> MessageChannel.jsm:964
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> Security Error: Content at
> moz-extension://d4407264-545f-41f9-92f9-d94798a6565e/ may not load data
> from blob:null/eb3ad061-b104-4914-b664-82d6d6dc5da0.
> [Show/hide message details.] sender.page is undefined
> MessageChannel.jsm:964
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Use of nsIFile in content process is deprecated. NetUtil.jsm:302:12
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Source map error: TypeError: NetworkError when attempting to fetch
> resource.
> Resource URL: https://a-v2.sndcdn.com/assets/css/app-72c259c3.css
> Source Map URL: http://ent/web-sourcemaps/app-72c259c3.css.map[Learn More]
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> uncaught exception: undefined
> TypeError: window is null WebRequestContent.js:124:7
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> TypeError: docShell.failedChannel is null content.js:670:13
> Error: Could not establish connection. Receiving end does not exist.
> background.js:1:417
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Security Error: Content at
> moz-extension://c39200d0-a9ee-4994-9d18-8b638a9dfee4/background/background.html
> may not load or link to
> chrome://mozapps/skin/extensions/extensionGeneric-16.svg.
> Security Error: Content at
> moz-extension://c39200d0-a9ee-4994-9d18-8b638a9dfee4/sidebar/sidebar.html?style=mixed
> may not load or link to
> chrome://mozapps/skin/extensions/extensionGeneric-16.svg.
> Error: Could not establish connection. Receiving end does not exist.
> background.js:1:417
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> Error: Could not establish connection. Receiving end does not exist.
> background.js:1:417
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> Error: Could not establish connection. Receiving end does not exist.
> background.js:1:417
> uncaught exception: undefined
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Error: Invalid tab ID: 69
> ext-browser.js
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> [Show/hide message details.] Promise resolved after context unloaded
> content_script_bundle.js:1
> Error: WebExtension context not found!
> ExtensionParent.jsm:1009:13
> Error: Could not establish connection. Receiving end does not exist.
> background.js:1:417
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> TypeError: this.highlighterEnv is null markup.js:243:9
> Use of Mutation Events is deprecated. Use MutationObserver instead.
> ExtensionContent.jsm:533:1
> TypeError: this._refMap is null walker.js:290:5
> An iframe which has both allow-scripts and allow-same-origin for its
> sandbox attribute can remove its sandboxing.
> stream
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
> remote resource at
> https://api-v2.soundcloud.com/promoted/users?device_locale=en&client_id=3Goi9X5NOF7g1ofGbmYEkpveejwvlqjd&app_version=1526649907&app_locale=en.
> (Reason: CORS request did not succeed).
> Loaded for the first time, injecting the scripts inject.js:37:5
> Injecting vendor/jquery.min.js inject.js:61:7
> [Show/hide message details.] Unchecked lastError value: Error: Could not
> establish connection. Receiving end does not exist. inject.js:30
> Injecting core/content/reactor.js inject.js:61:7
> Injecting core/content/filter.js inject.js:61:7
> Injecting core/content/util.js inject.js:61:7
> Injecting core/content/connector.js inject.js:61:7
> Injecting connectors/soundcloud.js inject.js:61:7
> Injecting core/content/starter.js inject.js:61:7
> Tab 67: Remove controller for SoundCloud connector main.js:349:4
> Tab 67: Created controller for SoundCloud connector controller.js:588:6
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
> remote resource at
> https://cf-hls-media.sndcdn.com/media/31763/79410/CXkaWihz0chF.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi9DWGthV2loejBjaEYuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTUyNjg5NDQ0NX19fV19&Signature=jsOyy3BgWOoaxrYPTa6Kz6Fb-nBWr787VMxCZG749iG29B~82hQ40VtGSeI8SCboSTxeJ~YUmZ9dTP1L-HfTx1lrQ9G6BQIRxzskxbUHh8dYLEGVI3I1Vr1LUMXbfI9FOXUbYmzZNA4gkvFnzjGEM-Roc32M0l3aBpXz0SDDxZTRgpXu4pkoRlxr1mYdmwGau~88po-w9xmBTF6rijpZLtsbt5YSzPSGpx7DL7dLy~zzcmYaP0wq861gIKdLlxZcscWoalG9wVDBw7r8eOLJSikqycvK9oQJLIHb2Mq~93O3Eum51V4H4d1SkAhlYFJkAZoMzkq0t0WzYAik5syjnQ__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ.
> (Reason: CORS request did not succeed).
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> [Show/hide message details.] NS_ERROR_FILE_CORRUPTED:
> app-dd17de5-80c4f85-3.js:26
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> [Show/hide message details.] NS_ERROR_FILE_CORRUPTED:
> app-dd17de5-80c4f85-3.js:26
> Webconsole context has changed
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> NS_ERROR_FILE_CORRUPTED: app-dd17de5-80c4f85-3.js:30:11423
> [Show/hide message details.] NS_ERROR_FILE_CORRUPTED:
> app-dd17de5-80c4f85-3.js:26
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing
> youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> NS_ERROR_FILE_CORRUPTED: app-dd17de5-80c4f85-3.js:30:11423
> [Show/hide message details.] NS_ERROR_FILE_CORRUPTED:
> app-dd17de5-80c4f85-3.js:26
> Web Scrobbler: Video element is missing
> youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated handlers.js:1987
> Web Scrobbler: Video element is missing youtube.js:216:4
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated handlers.js:1987
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> NS_ERROR_FILE_CORRUPTED: app-dd17de5-80c4f85-3.js:30:11423
> [Show/hide message details.] NS_ERROR_FILE_CORRUPTED:
> app-dd17de5-80c4f85-3.js:26
> Web Scrobbler: Video element is missing
> youtube.js:216:4
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> NS_ERROR_FILE_CORRUPTED: app-dd17de5-80c4f85-3.js:30:11423
> Web Scrobbler: Video element is missing youtube.js:216:4
> [Show/hide message details.] Error processing windowTypes: This property
> is deprecated
> handlers.js:1987
> [Show/hide message details.] NS_ERROR_FILE_CORRUPTED:
> app-dd17de5-80c4f85-3.js:26
> Error: Promised response from onMessage listener went out of scope
> background.js:8:1517636
> Web Scrobbler: Video element is missing youtube.js:216:4
> Web Scrobbler: Video element is missing
> youtube.js:216:4
> [Show/hide message details.] [Exception... "Component returned failure
> code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"
> nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
> resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
> line 63"  data: no]
> Web Scrobbler: Video element is missing
> youtube.js:216:4
> Web Scrobbler: Video element is missing youtube.js:216:4
> NS_ERROR_FILE_CORRUPTED: app-dd17de5-80c4f85-3.js:30:11423
> [Show/hide message details.] NS_ERROR_FILE_CORRUPTED:
> app-dd17de5-80c4f85-3.js:26
> Web Scrobbler: Video element is missing
>

not sure how useful this is, or if it's what you're looking for.

thanks.

**Comment by myfonj** [comment]
For me (Fx Nightly 62) scrobbles are being sent properly, badge properly visually reacts to supported sites, but doorhanger always says "not supported" (bandcamp):

![image](https://user-images.githubusercontent.com/1761395/40711570-d431359e-63fb-11e8-9fae-592d62a51bdb.png)

<details>
<summary>Start of the Error log (just warns and errs)</summary>
<pre>
Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered. components.manifest:165
Successfully compiled asm.js code (loaded from cache in 1852ms) vendors.min.js
Successfully compiled asm.js code (loaded from cache in 55ms) vendors.min.js
Successfully compiled asm.js code (total compilation time 2ms; not stored in cache (too small to benefit)) vendors.min.js
Successfully compiled asm.js code (loaded from cache in 15ms) openpgp.js
Successfully compiled asm.js code (loaded from cache in 6ms) openpgp.js
Successfully compiled asm.js code (total compilation time 2ms; not stored in cache (too small to benefit)) openpgp.js
Unchecked lastError value: Error: Script 'moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/data/tpl/login.js' result is non-structured-clonable data
index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: Error: Message manager disconnected index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: Error: Invalid tab ID: 45
index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. inject.js:30
pingAndInject/&lt;
moz-extension://995a3fe9-a34a-4c09-975b-818e0d1a5b3b/core/background/inject.js:30:4
Unchecked lastError value: Error: Script 'moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/data/tpl/login.js' result is non-structured-clonable data index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: DataCloneError: The object could not be cloned. controller.js:446
notifySongIsUpdated
moz-extension://995a3fe9-a34a-4c09-975b-818e0d1a5b3b/core/background/controller.js:446:4
Unchecked lastError value: Error: Script 'moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/data/tpl/login.js' result is non-structured-clonable data index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: Error: Missing host permission for the tab
index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unable to bind Libre.fm scrobble-service.js:47:6
Unchecked lastError value: Error: Script 'moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/data/tpl/login.js' result is non-structured-clonable data
index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: Error: Message manager disconnected
index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: Error: Invalid tab ID: 53
index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. inject.js:30
pingAndInject/&lt;
moz-extension://995a3fe9-a34a-4c09-975b-818e0d1a5b3b/core/background/inject.js:30:4
Unchecked lastError value: Error: Script 'moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/data/tpl/login.js' result is non-structured-clonable data index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: DataCloneError: The object could not be cloned. controller.js:446
notifySongIsUpdated
moz-extension://995a3fe9-a34a-4c09-975b-818e0d1a5b3b/core/background/controller.js:446:4
Unchecked lastError value: Error: Script 'moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/data/tpl/login.js' result is non-structured-clonable data index.min.js:9325
[84]&lt;/ScriptExecution.prototype.createScriptCallback/&lt;
moz-extension://4cdbbae2-3bff-4ea7-8b79-3c6f15225bfc/index.min.js:9325:7
Unchecked lastError value: DataCloneError: The object could not be cloned. controller.js:446
notifySongIsUpdated
moz-extension://995a3fe9-a34a-4c09-975b-818e0d1a5b3b/core/background/controller.js:446:4

</pre>
</details>

**Comment by BilliAlpha** [comment]
Can confirm,
The scrobbler sends scrobbles fine on youtube with Firefox Developper Edition (62.0b8) but when clicking the icon it says "not supported".
I cannot skip or edit scrobbles.

**Comment by myfonj** [comment]
So probably #1668 ?

**Comment by BilliAlpha** [comment]
Yes, sorry, didn't see the other issue.
