### ISSUE TITLE
support for hoopladigital.com

### ISSUE THREAD

**Issue by floorjoist** [web-scrobbler/web-scrobbler#1636]
please add support for hoopladigital.com (library media streaming service)

**Comment by brandonjp** [comment]
@floorjoist I've been scrobbling hoopla since April using this: https://github.com/brandonjp/web-scrobbler/commit/65365dc8af0d0f0653843254701552981a21b97b  Works mostly well, except for a few issues. The main issue is that if you're switching from listening to an audiobook to a music album, you have to refresh the hoopla page.  And an occasional issue if the album or artist has a hyphen in the name, it's harder to automatically guess/parse the metadata accurately.  

If you're interested in trying and need help, lemme know.

**Comment by inverse** [comment]
@brandonjp Wanna contribute your work to the core? Then we can close this issue?

**Comment by hornbuckle** [comment]
@inverse This issue can be closed, as well. 🙂

**Comment by inverse** [comment]
Thanks!
