### ISSUE TITLE
Scrobble filters (Remastered, Explicit)

### ISSUE THREAD

**Issue by thomwim** [web-scrobbler/web-scrobbler#1643]
On YouTube, the add-on has a filter that removes "official video" from the tags. Can you extend this feature into other websites?

Or remove the following case-sensitive phrases from track or albums: "explicit", "remastered" (with any year),...

**Comment by inverse** [comment]
This could be extended to other sites. The whole filter logic could be made extendable via the options to allow selection to use per-connector. however this is a significant overhaul.

**Comment by thomwim** [comment]
Okay, for now I'll edit the tags.

**Comment by thwaller** [comment]
I question this.... the portion of "official video" I do not. However, "explicit" is in fact a different recording from the clean version. Now "remastered", that is technically a different resulting recording, but all said and done is the same.

My point... please consider in detail the removal of relevant extra title information and how it relates to the recording and the differences between the other possible "versions" of said recording.

**Comment by revalenz** [comment]
> I question this.... the portion of "official video" I do not. However, "explicit" is in fact a different recording from the clean version. Now "remastered", that is technically a different resulting recording, but all said and done is the same.

But for example, Amazon music shows "[Explicit]" for every song that has explicit content, even if a clean version doesn't exist. (And also in many albums that have at least one explicit song) And even if it exists, the clean version is the one that should have a special suffix, since the "Explicit" version is usually the original song. 


It would be great if you can support maybe global filters configurable by the user. (Like a list of words to remove everywhere) (Maybe a list of "suffixes" to remove everywhere?)
