### ISSUE TITLE
I haven't the possibility to connect my account

### ISSUE THREAD

**Issue by moldputrefaction** [web-scrobbler/web-scrobbler#1669]
Hey !

I'm so sorry if I'm not in the good section, but I haven't found an other link to speak about my problem...

My PC is dead, and for the moment I have an old PC (Windows Vista)
I have Chrome with the Web Scrobbler extending but problem : I haven't the possibility to add my accounts ID 

What's the problem ? my Chrome is too old ?

**Comment by moldputrefaction** [comment]
https://image.noelshack.com/fichiers/2018/27/3/1530657645-sans-titre.png

**Comment by Xalaxis** [comment]
I can't be sure, but this most likely has something to do with it.  As per [Chrome's blog post](https://chrome.googleblog.com/2015/11/updates-to-chrome-platform-support.html) there have been no functionality or **security updates** since April 2016.

I strongly recommend you stop using Chrome and switch to Firefox which still has [one more month of security updates left](https://support.mozilla.org/en-US/kb/end-support-windows-xp-and-vista).  By that point hopefully your computer will be repaired.  The extension may also work properly under an updated Firefox install.

**Comment by moldputrefaction** [comment]
I need Firefow 53.0 for the Web Scrobbler, arf

**Comment by alexesprit** [comment]
Try to use at least Firefox 58

**Comment by Xalaxis** [comment]
@alexesprit They can't because no newer versions are supported for Vista.

**Comment by inverse** [comment]
So due to the lack in support for Chrome/FF Vista is no longer supported. Should this go into some Known issues section than?
