### ISSUE TITLE
Notifications are not silent when using native notifications

### ISSUE THREAD

**Issue by Xalaxis** [web-scrobbler/web-scrobbler#1670]
In the latest builds of Chrome, the notifications system now hooks into the built-in Windows 10 panel.  Song change notifications are now no longer silent, so the notification call is most likely missing the 'silent' attribute in some manner.

### Expected behavior
On song change, the notification about the newly recognised song should not trigger a notification sound.

### Current behavior
On song change, the new song is displayed and a notification sound also occurs.

### Possible solution

The code [here](https://github.com/web-scrobbler/web-scrobbler/blob/48761ea87cf6adc2b6ec7c659e9e127fdd547c04/src/core/background/notifications.js#L105) needs to be changed most likely.

https://developer.chrome.com/apps/notifications#type-NotificationOptions is the place to go for the spec, but I don't see any obvious 'sound' aspect other than the 'priority' field.  Perhaps this could be related somehow?

### Environment
* Version used: 2.5.0
* Browser name and version: Google Chrome Version 69.0.3472.3 (Official Build) dev (64-bit)

**Comment by n00bhax** [comment]
Could you just make the notification optionable?

**Comment by mirobartovic** [comment]
I have recently installed the Web scrobbler extension but did not notice the desktop notifications option. Took me a while till I realized what is causing the annoying notifications of a new song. The problem is that I can't silence them in Chrome as with notifications from web pages, only whole Chrome in Windows 10 settings. So the option to silence them in the extension settings would be mostly welcome. With the current behaviour I had to disable them.
