### ISSUE TITLE
Mixcloud - simple bug with "artist"

### ISSUE THREAD

**Issue by Mavoy** [web-scrobbler/web-scrobbler#1713]
This one is simple, I think. It didn't happen during my previous Mixcloud session a couple days ago. When I'm listening to radio show on Mixcloud (for example, this one https://www.mixcloud.com/NTSRadio/quiet-storm-11th-september-2018/) and the tagged song is playing, the extension recognizes as artist... "[ARTIST X] - buy" and obviously it won't find the album (I have to remove "buy" manually everytime). Looks like "buy" is connected to artist tag somehow, please find a way to remove it.

First time posting, so I'll just add I love this extension. One of must haves for me!

**Comment by alexesprit** [comment]
The "Buy" suffix is removed by the extension. I updated the function that does cleanup, and I hope the issue is fixed. Unfortunately, I cannot reproduce the issue, and I have no extension logs to find out the reason why the extension does not remove the "Buy" suffix (that's why the logs are really, REALLY important).
