### ISSUE TITLE
Sign in notification

### ISSUE THREAD

**Issue by iiw** [web-scrobbler/web-scrobbler#1740]
Hello. When I not logged in every time I start browser I receive notification about it. It's annoying. I using this extension at only one of my pc's with chrome. Can you make option to disable this notifications at all?

**Comment by alexesprit** [comment]
Why do you keep the extension if you don't use it?

**Comment by iiw** [comment]
because I using chrome on different pc's with sync. and I want scrobbler be only at few of them

**Comment by inverse** [comment]
@iiw what happens if you disable an extension? does that get synced across devices?

**Comment by iiw** [comment]
@inverse yes.

**Comment by alexesprit** [comment]
What about an ability to show auth notification up to X times?

**Comment by iiw** [comment]
> What about an ability to show auth notification up to X times?

How it will look like?

**Comment by iiw** [comment]
> @inverse yes.

btw, it's not about how this extension works. All extensions works so, because browsers syncs their extensions state (enabled or disabled)

**Comment by alexesprit** [comment]
The extension will display the notification, for example, three times after installation. That means, if you start your browser, it will display notification on first, second, and third launches. Next time an user starts a browser, the extension will not display auth notification. It's good for users who decided to ignore notifications. :)

I think, it's not a bad way, because authentication is not bound to notifications as it was before. Users can still sign in to scrobbling services via the options page, even if notifications are not displayed.

A separate option is a bad thing, IMO.

**Comment by iiw** [comment]
Yeah, good idea.
