### ISSUE TITLE
from Jamendo it no longer srobbelt

### ISSUE THREAD

**Issue by onkellu** [web-scrobbler/web-scrobbler#1809]
for almost 2 weeks there is no more scrobbelt from Jamendo to Last.fm

### Expected behavior
the page of Jamendo has changed and I ask for a review
i am not technically experienced enough to give a solution to the problem

### Current behavior
Nothing happens that I can see.
the scobbling should be restored

### Possible solution
i'm not a technician and i can't conjure a solution out of a hat.
??

### Steps to reproduce (for bugs)
https://www.jamendo.com/album/177674/el-aullido-del-lobo
i can't provide code

My Browser Firefox 63.0 64Bit for Linux Mint-1.0, my operating system is Linux Mint 18.1

1.
2.
3.

### Context
What should I do if the scrobble doesn't work?

### Steps for resolving the issue

I made
it didn't help.

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment
<!---
* Version used:
* Browser name and version: My Browser Firefox 63.0 64Bit for Linux Mint-1.0, my operating system is Linux Mint 18.1

SORRY, i can't speak english and have to help myself with a translated one, which is not so easy, because i only understand half of it

**Comment by NamJinWoo** [comment]
I think Play button and TrackArt is not working.

So, I fixed it like this:
Connector.isPlaying = () => {
	return $('.js-player-play-pause > .icon-pause').length !== 0;
};

Connector.getTrackArt = () => {
	return `${$('.hero-cover').find('img').attr('src')}`;
};

I compiled it in my local pc, and it works now.

If you need more help, please comment here.

Thanks:)

**Comment by onkellu** [comment]
Hi NamJinWoo, First of all, thank you for your efforts.
i can't do anything with your signs because i don't know where to find them and then change them.
i think it has changed on the jamendo side what i can't see as a layman, also i have no idea of technical connections and their improvement
i also think the problem is not with me but with jamendo.

the problem what had existed until recently with the page You Tube has then been corrected without doing mine and it works again...
This was done by programming by Git Hub.

sorry my english is very bad and I have translated with translater.

**Comment by KwonDae** [comment]
Hi onkellu, I hope this comments will help you.
in` /src/connectors/jamendo.js`

> Connector.playButtonSelector = '.js-player-play-pause > .icon-play';

this part should change by 

> Connector.isPlaying = () => {
> 	return $('.js-player-play-pause > .icon-pause').length !== 0;
> };
> 

In my opinion, the isPlaying function must bring in a replay display with an id of icon-pause when the song is playing on the jamendo site in order to communicate whether the song is currently playing.
such as, 
![image](https://user-images.githubusercontent.com/33443660/48953051-d7815180-ef87-11e8-8714-26332581f2d7.png)

this img is jamendo's state when it is working.
Now, if it is an icon-pause, I think the song is playing, so I have to get that state.

Second, We want get a img about TrackArt
in` /src/connectors/jamendo.js`

> Connector.trackArtSelector = '.js-full-player-cover-img';

this part should change by 

> Connector.getTrackArt = () => {
> 	return `${$('.hero-cover').find('img').attr('src')}`;
> };

beacuse we want get a img, So we should get **img src** in trackArt img.
![image](https://user-images.githubusercontent.com/33443660/48953368-fb916280-ef88-11e8-9cb3-befcf52e2210.png)
in jamendo, the trackArt img is in that point. so we should get src like that method.

If you find any mistakes or have questions, I would appreciate your comment. thank you :)

**Comment by NamJinWoo** [comment]
In addition, Thank you @KwonDae for the description for my code. You did a great job ^__^

**Comment by onkellu** [comment]
Thanks a lot Jinwoo (NamJinWoo) and KwonDae, for your effort in explaining to me how to solve this problem. I wanted to explain something:
My problem was that i don't know where to find these codes to be able to change them, so i can't implement the codes and the changes and if I could find the codes and change something, maybe do something wrong, then nothing works at all anymore.😖☠
So I am happy and grateful, if I understood it right, that you Jinwoo penn, that you have corrected the code and the improvement will appear in the next release.
The current version from the Web Scrobbler is 2.9.0 (this version is from 18. november 2018)
So I can only wait for the new version and then that everything works as desired again.

Thank you again for your effort..!! 🍻

have a nice weekend 🙋‍♂️

**Comment by alexesprit** [comment]
Jamendo was fixed recently.
