### ISSUE TITLE
All Scrobbling Down   

### ISSUE THREAD

**Issue by TigermaskV** [web-scrobbler/web-scrobbler#1954]
all of my scrobbling ability is gone   no matter what site I use 
 even Universal scrobbler  and  all sites that web version would work  one does not  work and the icon  just goes orange   and only Spotify works  no other  site  

iv tried to reauthenticate   20 times 
### Expected behavior

until  the past few days, these were all working  fine  

### Current behavior

Nothing is working 

### Steps to reproduce (for bugs)

1\.
2\.
3\.

### Steps for resolving the issue

-   [ ] Reauthenticate on Last.fm
    
    
    
-   [ ] Try to use unpacked extension from latest master
    
    
-   [ ] Check other issues for duplicates

### Environment

-   Version used:
-   Browser name and version:  Chrome

**Comment by muffinigans** [comment]
Same issue here -- at first it kept asking to re-authenticate, now it's not working at all, with a yellow icon on VK and YouTube (where I primarily scrobble). When I check, it says I'm still logged in to my Last.fm account, so I'm not sure what the issue is. The scrobbler recognizes songs and notifications pop up for them, but it doesn't scrobble.

I'm using Firefox on a Windows 10 PC. I have this extension at work in Chrome and it works fine there (though it had the same re-authentication hiccups a while ago).

**Comment by alexesprit** [comment]
Is it still an issue?

**Comment by ksbrar** [comment]
Same issue here.

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/david-sabata/web-scrobbler/wiki/Debug-the-extension
