### ISSUE TITLE
Consider "- X Remix" the same as "(X Remix)"

### ISSUE THREAD

**Issue by pgl** [web-scrobbler/web-scrobbler#1984]
**The issue**
Recently I imported my Soundcloud favourites into Spotify. Spotify seems to generally use the format "- X remix" for remixes, whereas Soundcloud uses the format "(X remix)".

**The solution I'd like**
When searching for an already-scrobbled track, I'd love it if the two formats were considered equivalent.

**Comment by alexesprit** [comment]
So, you propose to normalize track title using only one of the formats, right?

For example, "AAA - X remix" will be converted to "AAA (X remix)", and "BBB (X remix)" will be untoched.

If so, I'm for the "(X remix)" one, because it's more common format. "- X remix" is a quite odd.

**Comment by pgl** [comment]
I guess yes, that is what I'm proposing. Although I didn't quite realise it before.

And I agree, "(X remix)" seems much more common to me - it's used on Soundcloud and YouTube more commonly, although that's just personal experience.

Ironically...

![image](https://user-images.githubusercontent.com/1181139/58101667-57f3d880-7be0-11e9-95c2-36fbc9e4f126.png)

**Comment by alexesprit** [comment]
Thanks for the info. I'll take a look at it.

**Comment by alexesprit** [comment]
I've added a new rule to Spotify metadata filter to replace remix suffix. This rule applies to Spotify connector and few ones use the same filter (e.g. Deezer). I think it fully resolves the issue, because the "-X Remix" format is Spotify-ish, and (probably) no one uses such format. Although, it can be easily extended to work on other websites or even globally.

<details>
  <summary>Screenshot (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/58194809-30c80480-7ccf-11e9-9570-90db0f5a5d73.png)

</details>

I noticed some tracks on Spotify named "Track title - Remix", e.g. the one from [this album][0]. How should we handle such tracks? I have two options:
1. Remove "- Remix" suffix completely.
2. Replace "-Remix" to "(Remix)".

Don't really know which option is preferred. The first one is quite good, but we miss the information a track is a remix actually. On the other side, with the second option, "Track title (Remix)" is not much informative, as we don't know the remix name, but we know it's a remix.

[0]: https://open.spotify.com/album/38kpkGLuPr1nNfD3iEyOlJ

**Comment by pgl** [comment]
Brilliant, thanks!

I would choose the second (replace "\s*-\s*Remix" with " (Remix)", because if I saw a notification that Track X was playing, and it was different from the standard track, I would be a bit surprised and possibly annoyed. Although of course that's just my personal feeling.

**Comment by alexesprit** [comment]
I'm for the second option too.

I added another rule to replace "- Remix" with "(Remix)":
<details>
  <summary>Screenshot (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/58239163-3ebe6980-7d51-11e9-8352-6439bdce25b7.png)
</details>

Will push changes in a few minutes. It won't be released immediately, so you can download the extension from the master branch and enjoy the automatic replacement.

**Comment by pgl** [comment]
Ace. Thanks again.
