### ISSUE TITLE
Podcasts outside Play Music

### ISSUE THREAD

**Issue by ethanblomgren** [web-scrobbler/web-scrobbler#2154]
How hard would it be to keep podcasts from being scrobbled from Spotify, etc? Does Spotify even treat podcast traffic differently than music? I don't know how you would write a script for that, but if you made one it would be a helpful addition to this already great extension. Ignoring podcasts from other platforms manually as they're played isn't too challenging, but having an automated process do it would be convenient.

**Comment by alexesprit** [comment]
@ethanblomgren Hi!

First of all, all issues related to the extension should be posted [here][issues].

Technically, Spotify podcasts can be detected by artist/track URL (podcasts URLs have a `https://open.spotify.com/show/*` format).

The open question is how to manage scrobbling Spotify podcasts? We have an option which applies to Google Play Music only. So, we can add a new option for Spotify connector exclusively, or rework the current one to make it apply for both GPM and Spotify (and to other connector in future).

https://github.com/web-scrobbler/web-scrobbler/issues

**Comment by alexesprit** [comment]
Personally, I would go with the second option.

This could be done by adding new function for connectors, e.g. `Connector.isPodcast`; returns `false` by default; should return `true` if a podast is playing, `false` otherwise.

The function value is sent to the core as well as other data (track info etc), and the core allows or disallows scrobbling podcasts based on a new (global) preference.

**Comment by jaccarmac** [comment]
Doesn't quite lint yet, but I got some initial code laid down based on the check from the GPM connector. Need advice on how to proceed.

**Comment by alexesprit** [comment]
Interesting the extension does not recognize podcasts. I noticed this while testing the relevant PR on Spotify (GPM podcasts are blocked for me). This is not intentional behavior, though.

I splitted the logic in Spotify connector to skip ads and podcasts separately, and will push changes after the PR gets merged.
