### ISSUE TITLE
Option for scrobbling only the first/main artist

### ISSUE THREAD

**Issue by fmontesino** [web-scrobbler/web-scrobbler#2588]
**Describe the solution you'd like**
It'd be nice to have a configuration checkbox (or similar) to strip all secondary artists (after the first comma).
This can give some people (like me haha) a cleaner scrobble, as last.fm doesn't recognise Artist 1, Artist 2 a scrobble for Artist 1

**Comment by alexesprit** [comment]
See my comment: https://github.com/web-scrobbler/web-scrobbler/issues/2608#issuecomment-720393528. I think it's a better way to resolve the issue (I hate new options).

**Comment by flickur** [comment]
The thing is that just using the first artist in Spotify would result in more correct tags 99% of the time. Spotify themselves ignore the other credited artists in their track display since it's correct that way, as seen on the screenshot. If there's need to mention the featuring artist on the song name, it's usually already there on Spotify.

![image](https://user-images.githubusercontent.com/40724723/106357144-f371a200-630c-11eb-8beb-eb9e0f56fcf5.png)
