### ISSUE TITLE
Could you release newer version for firefox?

### ISSUE THREAD

**Issue by d3m3vilurr** [web-scrobbler/web-scrobbler#2633]
other browers already updated to `2.37.1`.  but firefox verison is still `2.36.1`.

**Comment by alexesprit** [comment]
Unfortunately, no, it was blocked by AMO reviewers.

**Comment by alexesprit** [comment]
The only thing I can do now is to upload an XPI file (v2.38.0) to GitHub Releases.

**Comment by d3m3vilurr** [comment]
oops.. I got it.
uploading xpi is nice to me in this case.

**Comment by alexesprit** [comment]
I've added an XPI file for v2.38.0.

**Comment by mzfr** [comment]
@alexesprit Did they give you any reason for failing the review process?

**Comment by alexesprit** [comment]
@mzfr sure.

<details>
  <summary>Summary (Click to expand)</summary>

Your add-on, Web Scrobbler 2.37.1, has been reviewed and did not meet the criteria for being hosted in our gallery.


Reviewer:
Wall-e

Comments:
This version didn&#39;t pass review because of the following problems:

1) This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a major security risk.
For more information, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page
Here are some examples that were discovered:
ui\startup\startup.js - L. 47

2) We do not see any opt-in at the installation of the add-on as requested in the previous review.
Please see this link to have an example of what we are requesting: https://extensionworkshop.com/documentation/develop/best-practices-for-collecting-user-data-consents/

3) Your add-on includes a third-party library. Please provide the origin of the exact library version you were using and make sure you are using an exact copy of the original maintainers&#39; release version. For more information, refer to https://extensionworkshop.com/documentation/publish/third-party-library-usage/
Remind that established libraries must be included from their official source, in their original format without any modification (changing the file name does not matter). Please note that only stable releases are acceptable (not beta, pre, RC, dev etc) and that third party CDNs are not considered official sources.
Please provide us with valid links to the third party library you are using.
To determine what are valid third part library links follow this link: https://extensionworkshop.com/documentation/publish/third-party-library-usage/#how-to-determine-the-third-party-library-link



This version of your add-on has been disabled. You may re-request review by addressing the reviewer's comments and uploading a new version at https://addons.mozilla.org/en-US/developers/addon/web-scrobbler/versions
</details>

**Comment by alexesprit** [comment]
Still not approved. :(

<details>
  <summary>Screenshot (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/100537436-c6840e80-3239-11eb-9517-580534a11f15.png)
</details>

**Comment by sc113** [comment]
Any updates on this one? Still would be glad to get XPI

**Comment by alexesprit** [comment]
No, it's still not signed.

**Comment by alexesprit** [comment]
I contacted with AMO reviewers, and they said I should fix review issues even if I want to distribute the extension manually.

I submitted an experimental build with no GA and with fixed issues that were found by the AMO reviewer.

**Comment by alexesprit** [comment]
v2.39.2 is available on AMO. :)
