### ISSUE TITLE
TuneIn site won't scrobble

### ISSUE THREAD

**Issue by DarkSunsetLove** [web-scrobbler/web-scrobbler#2661]
Hello,

Today I was listening to a station on TuneIn, and I realized it wasn't scrobbling, so I tried another station on the same site. It still wouldn't work. I tried another site to see if it would scrobble, which it did. I've tried three browsers. Firefox is the only one that plays the music, but it's not scrobbling. Can someone please fix this?

**Comment by DarkSunsetLove** [comment]
Forgot to add this but the metadata for the songs is showing

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by alexesprit** [comment]
What extension version do you use?

**Comment by thomwim** [comment]
Some stations are forced to open in a popup window, which will not scrobble.

For example, this station:
https://tunein.com/radio/Real-Rock-1039-The-Bear-s22335/

Due to a recent Chrome update, your browser no longer supports this station. Click on the icon below to keep listening with our new TuneIn popout player! Learn more about the update here.

**Comment by alexesprit** [comment]
@DarkSunsetLove could you check it again on Firefox and Web Scrobbler v2.39.2?

**Comment by DarkSunsetLove** [comment]
Hi!

Sorry for the late reply. I tried uninstalling and then reinstalling the extension on my Windows, and on the options page it says that I am not signed into last.fm even though when I log into last.fm and click Settings and then Applications, it says I've connected last.fm to the scrobbler. Also in Firefox, the icon that indicates whether or not a song is scrobbling was yellow and said there was an issue with scrobbling

**Comment by DarkSunsetLove** [comment]
> What extension version do you use?

I'm not sure what that means. I only recently downloaded the extension to my Windows computer, maybe a few weeks ago.

**Comment by alexesprit** [comment]
> I'm not sure what that means. I only recently downloaded the extension to my Windows computer, maybe a few weeks ago.

TuneIn scrobbling was fixed in v2.37.0 which is newer. But the last version on AMO was v2.36.1. That's why I asked about the version you use.

Now v2.39.2 is available on AMO, which should scrobble from TuneIn.

![image](https://user-images.githubusercontent.com/1119267/102972671-79c7e680-450c-11eb-95d6-84e63586bf14.png)

> Also in Firefox, the icon that indicates whether or not a song is scrobbling was yellow and said there was an issue with scrobbling.

It means authentication or Last.fm issues. To understand what and why happens, we need debug logs.
