### ISSUE TITLE
YouTube Music Scrobbling Issue

### ISSUE THREAD

**Issue by ImComingOniiChan** [web-scrobbler/web-scrobbler#2677]
**Describe the bug**
When a song is finished playing and the next song has begun to play certain fields are not updated correctly like the track title.

**How to reproduce**
1. Go to an album.
2. Begin playing a song.
3. Wait for the song to finish playing.
4. When the next song starts playing check to see if the fields have updated correctly in the extension popup.

**Expected behavior**
Fields should correctly update from one song to another.

**Screenshots**
Started to play a song.
![Vq0heJGSbR](https://user-images.githubusercontent.com/49422880/102701251-e17aea80-4209-11eb-8ba6-ed71c443ec91.png)

Initial song has finished playing and next song has started.
![NW95aID0hv](https://user-images.githubusercontent.com/49422880/102701262-0e2f0200-420a-11eb-9d93-908573322394.png)

**Debug logs**
[YouTube Music Debug Log](https://pastebin.com/Sws5miAY)

**Environment (please complete the following information)**
-   OS: (Windows)
-   Browser: (Brave)
-   Extension version: (v2.39.2)

**Additional context**
I don't know if this matters to the core issue but if you try this in a playlist like your "Your Likes" the fields that fail to correctly update are the track title and artist. The album field updates to the new song correctly.

**Comment by alexesprit** [comment]
Does it always happen for you? I can't reproduce this. Could you also make a screencast where you reproduce this issue?

**Comment by diegodeabreu** [comment]
I'm facing the same issue, the first time that occurred was last week. Sometimes I need to restart Chrome or even the computer but the problem persists.

**Comment by Mumumurilo** [comment]
Can confirm it also happens here. I've noticed it happening about two or three times last month, usually it identifies and changes the album cover and name, but the song name and artist won't change. I'm a macOS 10.15.6 user (Catalina).

![Screen Shot 2020-12-22 at 11 53 16](https://user-images.githubusercontent.com/8595653/102901430-605f6580-444c-11eb-88fa-30033d269ee2.png)

**Comment by bollandj** [comment]
Also having the same issue with the following environment:
- OS: Windows 10
- Browser: Chrome v87.0.4280.88
- Extension version: v2.39.2

I've been having this issue since I first started using YouTube Music about a month ago. It only seems to happen with certain albums/songs, and the issue will persist for that particular album/song through a browser restart (haven't tested if it still happens through a reboot yet).

Just a couple of extra points on the issue behaviour/steps to reproduce:
- If the issue affects an album, it affects every track on that album; i.e. whichever track you play first will be the one that continues to be scrobbled as YouTube Music 
- I can also confirm the behaviour noted by Mumumurilo regarding playlists; the album field will update but the artist and title will not

[Here's another debug log if it helps](https://pastebin.com/qnbk8hEa)

**Comment by alexesprit** [comment]
Interesting, looks like you receive the same song info from the YouTube Music connector.

But I still can't reproduce the issue. I followed steps from the first comment, but it work fine for me.

I also asked to record a screencast where this issue is reproduced.

By the way, is the tab with YouTube Music active or inactive when the song ends playing?

**Comment by ImComingOniiChan** [comment]
I have not had the time to record my screen but, it happens both when the tab is inactive and active from my experience.

**Comment by diegodeabreu** [comment]
I'm sending what happens to me.

https://user-images.githubusercontent.com/3492522/103034786-718b9d80-4544-11eb-9beb-674fb537e04e.mp4

**Comment by alexesprit** [comment]
@diegodeabreu Thanks for sharing the video! Now it's time to understand for me how to reproduce it for me. :D

**Comment by alexesprit** [comment]
I still can't reproduce the issue, but seems like I figured out why it does not work for others.

**Comment by alexesprit** [comment]
I made an attempt to fix the issue. Unfortunately, I can't reproduce it, and I can't verify it's fixed, so I ask you guys. :)

[web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/5761547/web-scrobbler-chrome.zip) 
[How to install the extension from a zip file][install-from-zip]

[install-from-zip]: https://github.com/web-scrobbler/web-scrobbler/wiki/Install-an-unpacked-extension

**Comment by Mumumurilo** [comment]
@alexesprit Thanks a lot, it seems like it's fixed! I'm on the third song and it is scrobbling correctly!

You should do a PR with it 😁

**Comment by alexesprit** [comment]
@Mumumurilo thanks for the info.
