### ISSUE TITLE
Requesting to add STATIONHEAD on scrobbling connector

### ISSUE THREAD

**Issue by chimooknology** [web-scrobbler/web-scrobbler#2879]

**Comment by willfolsom** [comment]
@chimooknology Is there a web player?

**Comment by chimooknology** [comment]
Hi! I don't actually seem to know if there is a web player. But i
discovered that when we are playing/listening to stationhead through web,
we get to track the scrobbles in lastfm since the spotify is connected on
stationhead, but only when we are using stationhead on laptop we get to see
the scrobbles i think.

**Comment by jfcabral** [comment]
Hi

From what I see, there doesn't seem to be a web player. STATIONHEAD seems to be a mobile application that leverages music streaming services:
> another crucial element of Stationhead’s approach is the fact the startup doesn’t have to make its own deals with the music labels. Instead, it integrates with existing streaming services — it launched with Spotify and recently added Apple Music.
> https://techcrunch.com/2017/11/29/stationhead

@chimooknology if you're using it with Spotify, you should only need to setup your Spotify <-> LastFM integration in order to have your scrobes sync with last fm.

For this reason I believe there's nothing to implement here. 
@alexesprit, what do you think of this?

**Comment by chimooknology** [comment]
Thank you for your response, i actually get to scrobble on stationhead
because of my Spotify is connected to lastfm, so when it plays on
stationhead it also plays on my spotify so the music scrobble on lastfm
since my spotify is connected to it. At first i didn't thought of it and i
just want to check if stationhead get to have an option to scrobble thru
web scrobbler but it's all good now. Thank you guys :)

**Comment by jfcabral** [comment]
Nice @chimooknology 😄 
Could you close the issue then?
Thanks
