### ISSUE TITLE
Remember unrecognized tracks to manually label them later

### ISSUE THREAD

**Issue by Dediqated** [web-scrobbler/web-scrobbler#291]
I had a lot of tracks in a youtube playlist playing while i was doing some other stuff. When i checked my last fm page for the last played tracks to favorite one track i saw that almost 15 tracks were not recognised apparently. So I didn't have them in my Recently Listened Tracks list which isn't what i want. I should have edited every track to be sure it got scrobbled correctly.

So the point is maybe there can be a list of tracks which are not recognised so the user can correct the tracks and fill in the list later. I saw at this issue: https://github.com/david-sabata/Chrome-Last.fm-Scrobbler/issues/245 that a new feature might be remembering user-entered artist/track so maybe combine these two?

**Comment by marsjaninzmarsa** [comment]
Related to #211

**Comment by inverse** [comment]
Could be part of the whole offline caching feature. A way to edit and try to submit

**Comment by RAM237** [comment]
Would be great to have this option not only for unrecognized tracks, but for anything you play.
E.g. played an album on Yandex Music, then verified everything is OK (or modified some stuff) - and submitted the whole pack of scrobbles. Hm..?

**Comment by alexesprit** [comment]
## Features
- Add unknown songs to the storage automatically
This happens if they reach scrobbling point (50% or 240 seconds) only.
- Add unscrobbled songs to the storage in cases when a scrobble service returns an error
- Edit and scrobble songs in the storage; remove songs from the storage
The extension is quite smart and it processes scrobbling errors, so it won't remove song if one of scrobbling services returns an error.

## Current limitations
- The "Scrobble all" button does nothing
I got stuck with batch scrobbling. :( It's quite hard task since we have multiple scrobblers, and we should not just scrobble songs, but also process possible errors.
- It's not integrated into the options page
I plan on redesigning the options page, so this feature will look more clear and natural.

## Further (but low priority) improvements
- Add a check for scrobbling unknown songs
Don't allow to scrobble unknown songs, if they aren't edited via a modal dialog.
- Add a feature to fetch album title from Last.fm
This could be useful to edit unknown songs.

Preview: https://github.com/web-scrobbler/web-scrobbler/tree/feature/scrobble-storage
Video: https://www.youtube.com/watch?v=qYkgx4PbN4Y (I recorded this video a while ago, so UI is quite outdated here).

Suggestions are welcome, as always.

![image](https://user-images.githubusercontent.com/1119267/84603255-ab912e00-ae95-11ea-8216-fbae302830ef.png)
