### ISSUE TITLE
Scrobbling to ListenBrainz from Tidal in an Opera tab works but not from the Opera "Player" in sidebar 

### ISSUE THREAD

**Issue by Lotheric** [web-scrobbler/web-scrobbler#2926]
Scrobbling to ListenBrainz from Tidal in an Opera tab works but not from the Opera "Player" in sidebar (https://www.opera.com/features/player-in-sidebar)

Windows 10
Opera 77.0.4054.203
Extension version: 2.44.0

**Comment by hans-juergen** [comment]
I don't know about Tidal, as I do not have an account there, but I can confirm that the new sidebar player in Opera does not scrobble YouTube Music either, and I guess it is the same for the other available streaming sites (Apple Music, SoundCloud) that do not have an internal scrobbling option like Spotify and Deezer which do scrobble without the Web Scrobbler while using the sidebar player in Opera.

I guess they do not work, because the currently playing track is only shown in a small popup window if you hover the player icon in the sidebar, see this screenshot:

![Opera Sidebar Player with YouTube Music](https://user-images.githubusercontent.com/4970867/126426092-3181fafd-596e-44f4-aa1b-b0b07239bd3b.png)

**Comment by fiuzatayna** [comment]
I'm having the same issue with the opera sidebar player for YouTube.

**Comment by alexesprit** [comment]
Not sure if it can be fixed.
