### ISSUE TITLE
Spotify  Not working

### ISSUE THREAD

**Issue by TigermaskV** [web-scrobbler/web-scrobbler#3292]
The  osng plays  the  icon is green  but never complates  i never the tick in the box

**Comment by yayuyokitano** [comment]
Hello, please check that spotify is set to show the full duration of the song, instead of being set to show the remaining duration of the song.
Currently, web scrobbler does not work properly with the remaining duration setting and it is the most common cause of your issue.
To switch between the two, simply click on the duration counter on the right side of the bar showing the progress of your song.
Can you verify if web scrobbler works or not with duration counter set to show full duration of the song?

**Comment by yayuyokitano** [comment]
I've already told you the most common solution is to set the spotify duration counter to show full duration.

If that does not solve your problem, then I cannot help you until you provide logs.
