### ISSUE TITLE
Frisky Radio

### ISSUE THREAD

**Issue by pedrojvaz** [web-scrobbler/web-scrobbler#3330]
Hello,

Could you support https://www.friskyradio.com (soon to be https://frisky.fm) online radio?
Current song/show is available at the bottom of the page.

Thanks

**Comment by inverse** [comment]
Not sure how feasible that is - are tracks displayed? I couldn't see anything

**Comment by pedrojvaz** [comment]
At the bottom it shows the current show being played, but not the track. Would this work?

**Comment by jbwharris** [comment]
@pedrojvaz @inverse I was able to get a connector working for frisky.fm. The main problem I ran into was that their play/pause button was switched using xlink:href. I wasn't able to get it to pick up the play behaviour off this button, but I did get it to work based on whether the song/artist meta box existed. So if the song were paused or not, it wouldn't actually know since it isn't tied to that button. There's also a pretty big blind spot in not having a paid account, so I don't whether the behaviour might differ. It's somewhat difficult to test, since so many of the songs are intentionally long, and the free tier doesn't really have skip functionality.

**Comment by inverse** [comment]
@jbwharris like it was an svg path? We have connectors that already use that if so

**Comment by jbwharris** [comment]
@inverse I did try searching the codebase for something to use with the deprecated `<use xlink:href="#icon-play_arrow"></use>` in an SVG, but if there's connectors you could point me to I'll see if I can get it working.

**Comment by inverse** [comment]
Will be in the next release!
