### ISSUE TITLE
Disable account per connector

### ISSUE THREAD

**Issue by KucharczykL** [web-scrobbler/web-scrobbler#3367]
**Is your feature request related to a problem? Please describe.**
Some services use their own scrobbling mechanism (e.g. Spotify, Deezer etc.). I have these enabled because of devices that don't support any other way. In a browser I have Web Scrobbler enabled with my Last.fm, Libre.fm and Listenbrainz accounts. When I listen in a browser tracks get duplicate scrobbles to Last.fm (or other services depending on the connected service).

**Describe the solution you'd like**
Being able to disable accounts per connector. This way I can, for example, disable scrobbling to Last.fm when I listen to Spotify in a browser but leave it enabled in Spotify itself for all the other use cases.

**Describe alternatives you've considered**
Either disable the connector or log out of the Last.fm account in Web Scrobbler.

**Additional context**

**Comment by inverse** [comment]
This is already supported :) Just go into the settings and expand options  and you'll be able to toggle each connector on and off.

![image](https://user-images.githubusercontent.com/713525/190607996-b79d9886-f0cf-4f37-b744-8956d69d09cb.png)

**Comment by KucharczykL** [comment]
I don't want to disable connector, I want to disable account for a specific connector. For example, for the Spotify connector, I want to disable scrobbling to Last.fm (while leaving it enabled for everything else).

**Comment by yellowJennifer** [comment]
I was going to submit a new feature request, but I found this, and this is literally what I also want. I'm not sure if I should submit a new issue since this is the same exact feature, so I'll post here first.

To clarify what the request is: 

Allow disabling scrobbling for different accounts on a certain connector. 
For example, I want to disable scrobbling for Spotify on Last.fm, but keep scrobbling on other connected accounts (Libre.fm, etc). 

I think this would be a good feature, because, for example, if one wants to use Web Scrobbler to scrobble Spotify plays (on the web player) to Libre.fm (or any of the connected accounts), but also has Spotify linked to their Last.fm account, this creates double scrobbles.
Unlinking Spotify from Last.fm would be a solution, but then that means scrobbles won't be automatic while playing Spotify on mobile/console/TV/etc.

A checklist with each account that is currently connected could be added to the Connectors' settings, if this is a feasible feature to add.
