### ISSUE TITLE
Scrobbling fail from Global Player 

### ISSUE THREAD

**Issue by jrveronez** [web-scrobbler/web-scrobbler#3405]
The extension does not recognize trakcs from Global Player (Radio X).

I'm listening from https://www.globalplayer.com/live/radiox/london/.

**Comment by forenta** [comment]
I'm not on any developer branch here - since I also noticed that the connector was no longer gripping while listening earlier, I took a quick look at the code there. It really no longer corresponds to what the global player delivers.

These are the parts be to pick up:

**Artist**
class `subtitle_36O7RaFl`
data-testid `show-info-subtitle`
title XX

**Track**
class `title_OmaPsNhv`
data-testid `show-info-title`
title XX

I would be happy if someone could take care of this. Maybe @alexesprit has time or someone else.
Thanks for all your commitment, friends!

**Comment by jrveronez** [comment]
Tested and approved, so I'm closing the issue.
Thank you guys!
