### ISSUE TITLE
Duplicate Scrobbles on Spotify

### ISSUE THREAD

**Issue by DarkMacek** [web-scrobbler/web-scrobbler#3434]
**Describe the bug**
The app is scrobbling spotify songs 2-3x each.

**How to reproduce**
1. Go to spotify
2. Play any playlist
3. See your last.fm page have many duplicates

**Expected behavior**
1 scrobble per song

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   Windows
-   Chrome 106.0.5249.119 
-   2.76.0
![lastfmScreenShot](https://user-images.githubusercontent.com/2748038/197081075-ea2a7158-9de6-4968-ac87-f062c2a0e72c.png)
[webScrobblerDebug.txt](https://github.com/web-scrobbler/web-scrobbler/files/9834645/webScrobblerDebug.txt)

**Comment by yayuyokitano** [comment]
I can see from the logd that it does indeed seem to scrobble twice, but it looks like its coming from different tabs.

Can you confirm that you do not have multiple tabs of spotify open?

Tabs not actively playing will still scrobble due to how spotify displays tracks playing elsewhere.

The third scrobble I would guess comes from spotify connection in last.fm, but it could be from something else, lets start with verifying theres only one tab scrobbling.

**Comment by DarkMacek** [comment]
I probably had two active tabs of Spotify at the time. The third seems a little odd though? (That was not an uncommon occurrence.)

**Comment by CennoxX** [comment]
Previously, Web-Scrobbler detected multiple open tabs. However, due to changes at Spotify, now the function [isMainTab()](https://github.com/web-scrobbler/web-scrobbler/blob/master/src/connectors/spotify.js#L77) does not work anymore, it returns true even if it is not the MainTab.
