### ISSUE TITLE
Firefox Store not updated

### ISSUE THREAD

**Issue by jee-r** [web-scrobbler/web-scrobbler#3537]
Hi,

Web-Scrobbler in  Firefox Store has not been updated since  Dec 12, 2022 (v2.82.2) 

https://addons.mozilla.org/en-US/firefox/addon/web-scrobbler/

I'm trying to install it from the build to get the latest version, but it's a pain to bypass signature checking on recent versions of Firefox. 

Could you please publish it :pray:

**Comment by yayuyokitano** [comment]
Hi,

2.83.0 (the oldest version not on firefox yet) was only released 9 days ago, and the push for that and more recent versions were all successful from our end.
This is on mozilla, who I think is planning on doing a manual review of the extension, and havent gotten around to it yet (presumably a holidays thing)
Will keep issue open until the issue is resolved regardless

**Comment by jee-r** [comment]
Okay. I was confused because I saw that all actions successfully passed but build was never released on the Mozilla store. 
Thank's for the clarification @yayuyokitano

BTW Happy new year

**Comment by yayuyokitano** [comment]
Happy new year!

I have now received an email from mozilla saying 2.85.0 is up, so this should be solved now.
