### ISSUE TITLE
Pop-up that asks for track / artist name automatically

### ISSUE THREAD

**Issue by leana8959** [web-scrobbler/web-scrobbler#3554]
**Is your feature request related to a problem? Please describe.**
I realized that the track and artist name are, at least on YouTube, a simple split of the title of the video at the character `-`. This frequently gets the track metadata wrong. I totally understand that it's *impossible* to create a parser that works for all titles, considering how there's an infinite way to name a video, hence the proposition.

**Describe the solution you'd like**
Have a pop-up whenever a song is detected, before submitting the scrobble.

**Describe alternatives you've considered**
Modifying metadata by hand. It's less automatic, considering that I have to check if metadata is parsed correctly. Even batch editing past entries on last.fm is a pain.

**Additional context**
To make this function less annoying, maybe we can also: 
 - make it opt-in in the extension preferences
 - make the pop-up easy to dismiss
 - remember personalized track metadata in the past, possibly binding it with the link (considering YouTube)
 - only pop up when the current song isn't found in a metadata database, which means the extension might have failed to parse the metadata
 - host saved metadata, so that one person editing the metadata would suffice

Thanks for your time and I appreciate this project and the devs making it possible :)

**Comment by yayuyokitano** [comment]
Greetings, thank you for getting in touch! So a lot of what you describe is already _kind of_ a thing in web scrobbler but not quite in the way you lay it out, but I'll answer to each of the things you mentioned in a bit more detail to see what changes you would like to see.

First of all, the metadata parser of web scrobbler is considerably more complicated than just splitting at -, but as you say titles are chaotic and we have not accounted for nor will we ever be able to account for all cases. If there are any patterns that are not recognized well by the extension, feel free to report those, new patterns are basically trivial to add if they do not directly contradict existing patterns.

Web scrobbler already remembers track metadata you have entered and confirmed for a track, nothing to add here.

The default behavior of web scrobbler is currently to not scrobble if the artist/track combo is not found on last.fm, which the user can opt out of with the "Force track recognition" option in the options. By default, there is no notification when a track is not recognized beyond the extension icon turning into a question mark, but the user can opt in to receiving a notification as well with the "Notify if track is not recognized" option.

However, as we use last.fm to check if the track exists, it is enough for one user to override and scrobble the track, and it will be recognized by web scrobbler for other users in future, and since some percentage of our users use force track recognition or simply do not care about the accuracy of the tags as long as its clear what is being scrobbled, incorrect titles coming from web scrobbler is unfortunately not uncommon.

As for hosting saved metadata, this is potentially possible in future (we are starting to reach a point where we could actually have funding for this), but there are a lot of moderation concerns connected to this, so this would have to be something that would have to be discussed carefully. It is an interesting idea, though. That said, it definitely belongs in a separate issue from this.

**Comment by leana8959** [comment]
Thank you for your exhaustive reply!

> However, as we use last.fm to check if the track exists, it is enough for one user to override and scrobble the track, and it will be recognized by web scrobbler for other users in future, and since some percentage of our users use force track recognition or simply do not care about the accuracy of the tags as long as its clear what is being scrobbled, incorrect titles coming from web scrobbler is unfortunately not uncommon.

Is it possible to mark songs that are being scrobbled with Force Track Recognition?  
Or is it possible to have an opt-in pop-up that asks for the metadata? It would be better to submit valid metadata, I prefer quality to quantity, having entries that are unreadable isn't really worth it. Not to mention that one person submitting the wrong information "pollutes" the entire service's dataset, essentially one person using Force Track Recognition makes everyone use Force Track Recognition (for the songs they listen to in common).

There are also videos from musicians that get scrobbled too, even when they aren't about music.  
I tried to disable scrobbling for that specific video, however, I still see Web Scrobbler scrobbling at every chapter of the YouTube video when I play it.  
I supposed they have been force scrobbled too?

> As for hosting saved metadata, this is potentially possible in future (we are starting to reach a point where we could actually have funding for this), but there are a lot of moderation concerns connected to this, so this would have to be something that would have to be discussed carefully. It is an interesting idea, though. That said, it definitely belongs in a separate issue from this.

I understand that hosting metadata can be complicated legally...  
I realized that it's very difficult to distinguish a machine parsed title from one submitted by a user without hosting metadata.  
If we host metadata, we can have a pool of titles that are parsed by Web Scrobbler, and another pool of titles that are human submitted. For a user who wants to have absolutely correct metadata like me, maybe we can alert them if the currently submitted song is only in the pool of the song that has been automatically parsed, or automatically choose to use the metadata from another user if the song in question is in the pool submitted by human.

Thank you for your time and have a nice day :)

**Comment by yayuyokitano** [comment]
> Is it possible to mark songs that are being scrobbled with Force Track Recognition?
The only way for us to do this would be to host our own server and do some basic but fragile math.

> Or is it possible to have an opt-in pop-up that asks for the metadata?
It is doable to have a setting like that.

One possible solution is to use another database such as musicbrainz, which has higher quality of data, but is not as extensive. Definitely has to be opt-in though.

> I supposed they have been force scrobbled too?
Most likely.

> I understand that hosting metadata can be complicated legally...
It is not really a legal issue, safe harbor laws should shield us from any legal problem. The problem is a safety one and a usability one.
Web scrobbler has ~100k users. We simply cannot assume these users will act in good faith, because they won't.
Without proper moderation, vandalism or even hateful messaging can easily make it through and our users be exposed to it, and maybe even unknowingly scrobbled by them.
In a worst case scenario, you could even consider someone like me, that has a handful of artists where I am one of a single digit number of last.fm listeners. If someone has it out for me and I were a little inattentive, they could dox me and literally get my personal information right up there in my own recent scrobbles by editing the tracks of these artists.
People could put advertisements in edits of popular videos as well, and I'm sure there are many other nasty possibilities I haven't even considered.
Once you get into the world of hosting user-submitted content things get very chaotic very fast, and you unfortunately have to be prepared for everything.
This is not to say it is definitely impossible, but it would have to be very very carefully considered. Due to the volume of users, its not like us devs stand any chance at going through every edit everyone makes ourselves either.

**Comment by leana8959** [comment]
> It is not really a legal issue, safe harbor laws should shield us from any legal problem. The problem is a safety one and a usability one.

Thank you for the explanation, I thought it was purely legal, but it's way more than that...
