### ISSUE TITLE
Apple Music connector not working

### ISSUE THREAD

**Issue by ryanclindborg** [web-scrobbler/web-scrobbler#3808]
Have never GitHub before so this is a first -

**Describe the bug**
Web Scrobbler won't recognise tracks via Apple Music, tracks not appearing/notifying when playing, not being logged on LastFM account.

**Expected behavior**
Tracks recognised and scrobbled, notification to pop up with song playing. 

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 113.0.5672.127

![image](https://github.com/web-scrobbler/web-scrobbler/assets/134901219/267d8855-fb0b-4813-9f53-4d931881f969)

**Comment by nulla2011** [comment]
I have the same problem.

OS: Windows
Browser: Chrome 113.0.5672.127
Extension version: 3.0.9

**Comment by franclecor** [comment]
I have the same problem. It recognizes my songs sometimes and not others.

**Comment by yayuyokitano** [comment]
Thank you for reporting!

I think I've found the cause, but having a bit of a hard time patching it, because the bug is happening like 1/50 - 1/100 reloads for some reason, but I think this is the kind of bug that will be more common on some machines than others.

Other than that i think this shouldnt be super difficult patch. As a temporary workaround, it seems like reloading the page sometimes fixes the issue.

**Comment by ryanclindborg** [comment]
Still can't seem to get the scrobbles working - I haven't even been able to get songs working intermittently via Apple Music. Have reloaded the page, deleted the extension and reloaded, and done a couple of full restarts and still no luck. 

Appreciate the effort/looking into it.

**Comment by yayuyokitano** [comment]
v3.0.10 has been merged with this patch, hopefully the issue is gone for good this time.
