### ISSUE TITLE
Deezer connector does not recognize new song when previous one finishes

### ISSUE THREAD

**Issue by mariomarinato** [web-scrobbler/web-scrobbler#3866]
**Describe the bug**
When listening to an album or playlist on Deezer, often the connector does not recognize the new song when the previous one finishes.  Sometimes it scrobbles the previous song again.

**How to reproduce**
1. Listen to an album or playlist on Deezer.

**Expected behavior**
When a new song starts playing, it is recognized and scrobbled.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Firefox
-   Extension version: 3.0.10

**Comment by yayuyokitano** [comment]
This should already be fixed by #3838 which was newly pushed in 3.0.11. 3.0.11 seems to be fully compliant with v2 behavior. Closing, please reopen if this still occurs once you release 3.0.11.
It will probably take a few days for mozilla to approve 3.0.11 judging from how things usually go with their review process.
