### ISSUE TITLE
YouTube connector unable to find unique ID on certain pages

### ISSUE THREAD

**Issue by LostLuma** [web-scrobbler/web-scrobbler#4045]
**Describe the bug**
The YouTube connector does not find certain videos' unique IDs.  
Due to this the extension is unable to load saved edits from storage using the unique ID.

**How to reproduce**
1. Visit an affected page, such as https://www.youtube.com/watch?v=vMddOrUGwDw
2. Open the console on the page
3. Click play
4. Note that any references to the unique ID in the logs are `null` instead of `"vMddOrUGwDw"`

**Expected behavior**
Web Scrobbler should correctly identify `vMddOrUGwDw` as the video's unique ID.

**Debug logs**
Content Script: https://files.lostluma.net/m6jzFQ.txt
Service Worker: https://files.lostluma.net/oy2DX8.txt

**Environment (please complete the following information)**
-   OS: Windows 11 Version 22H2 / Arch Linux
-   Browser: Mozilla Firefox 118.0a1 / Microsoft Edge 116.0.1938.54 / Google Chrome 116.0.5845.96
-   Extension version: 3.0.15

**Additional context**
I automatically create and distribute my saved edits file to a few friends, meaning I rely on Web Scrobbler finding unique IDs properly as I'd rather not have to update it in case eg. the video title changes.

**Comment by LostLuma** [comment]
Looking at the source it seems this is intended (from https://github.com/web-scrobbler/web-scrobbler/commit/658a30d7c320ee00f30cfba4a9ac1967e8dbdaa4), however this is very unintuitive ...
https://github.com/web-scrobbler/web-scrobbler/blob/7156eab10e30bc89b568d8ba8f011323a8129833/src/connectors/youtube.ts#L151-L157

**Comment by yayuyokitano** [comment]
Apologies, I thought I replied to this, but apparently I did not.
The reason this is happening is that when there are chapters web scrobbler scrobbles the videos chapters as individual songs, rather than the entire video as a whole (for stuff like compilations, full album streams, etc.)
As such, there cannot be a unique ID based on url alone, since youd have multiple songs on the same unique ID.
Issue these videos are being flagged as having multiple songs within them thanks to having chapters.
It's not a simple issue to fix, to be honest, but it has to be done. I have some ideas in my head but I'm not entirely sure which one to go with yet.
