### ISSUE TITLE
Issue with Youtube compatibility re Title and Artist 

### ISSUE THREAD

**Issue by TheProfessor860** [web-scrobbler/web-scrobbler#4240]
Have been scrobbling with you for a while but there appears to be an issue with pulling artists across today. 

There are artists that I have listened to thousands of times who are being pulled across as "Autechre-topic" rather than just Autechre as they have done previously./ 

Is there a way of remedying this?

**Comment by Ser-Erate** [comment]
I've experienced the same problem, it seems to be drawing directly from the channel name for artist rather than checking the description for auto-generated videos as it had done previously. I tried removing and re-adding the Web Scrobbler extension, but that didn't fix it. (And I forgot to save my edited tracks, so now it's even more of a problem.)
Strangely, none of my friends seem to have noticed it when I asked them.
Possibly related to the browser? Idk what browser you use, but to my memory I'm the only person I know who uses Web Scrobbler on Vivaldi Browser.

**Comment by glitchybunny** [comment]
There's a workaround for this issue here https://github.com/web-scrobbler/web-scrobbler/issues/4044#issuecomment-1686592815 until this gets fixed in the extension

**Comment by Ser-Erate** [comment]
Doesn't work for all artists, as some have the music on their official channel which has a different name than their band (For example They Might Be Giants' channel is called "ParticleMen"), but that definitely helps for most cases, Thanks!
