### ISSUE TITLE
Mullvad browser support?

### ISSUE THREAD

**Issue by Zepfanman** [web-scrobbler/web-scrobbler#4436]
I've been using the security-specialized Mullvad (Tor/Firefox) browser, but I can't get Web Scrobbler to connect to my ListenBrainz account. I've tried both account and local instance options. Would https://api.listenbrainz.org be the API url, and my account token? (It's not working either way.)

**Comment by yayuyokitano** [comment]
Hi!
While I download the browser and start to do some checks, have you ensured that you have clicked the popup at the top of the options menu to give permissions to web scrobbler?
There is a permission mozilla does not allow us to auto-grant that is essential for listenbrainz account login. Though I don't think this should affect the local instance login.

**Comment by Zepfanman** [comment]
Thanks for your reply. I don't think I'm getting a popup, but I've gone into add-ons management (about:addons) and  made sure all permissions are turned on for Web Scrobbler.

**Comment by yayuyokitano** [comment]
Got the browser installed and tested a bit.
It seems that the normal login doesn't work because it is reliant on cookies that mullvad kill.
You can use local instance though, but you have to use url `https://api.listenbrainz.org/1/submit-listens`
Not entirely sure why that decision was made back then, but done is done I guess.
Was able to get scrobble coming through to listenbrainz that way.
Please let me know if it works for you as well.

**Comment by Zepfanman** [comment]
Looking good so far. Thank you!!!

**Comment by yayuyokitano** [comment]
Glad to hear it! Closing, though feel free to reopen if something breaks.
