### ISSUE TITLE
Searching in the submenu of a YouTube channel results in an error.(/undefined)

### ISSUE THREAD

**Issue by onechu** [web-scrobbler/web-scrobbler#4581]
Searching in the submenu of a YouTube channel results in an error.

Searching from within a channel will result in a search with /undefined after the search term. If you type in a search term and press enter, it will always search with /undefined after the search term, so if you need to search because you can't use YouTube normally, you have to turn off the extension.

**Comment by yayuyokitano** [comment]
Unable to reproduce this, and seeing as web scrobbler does not really touch that part of the website in any way I fail to see how web scrobbler would even affect this in any way. Though weirder things have happened in software history.

Could this maybe be some intermittent bug caused by something unrelated that happened to line up with disabling web scrobbler?

Also, which browser (and version), OS, and web scrobbler version are you on?

Just in case, could you provide logs as specified [here](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension)

**Comment by onechu** [comment]
I listened to you and did some additional testing.

I'm using a YouTube ad-skipping extension called AdSpeedUp, and when I use it with Web Scrobbler, I get the symptoms you describe.

I have to turn off AdSpeedUp, or turn off Web Scrobbler, and the search works fine. The /undefine after the search term when searching within a channel happens when using both extensions.

I'll work on this further and post a log so you can provide it.

(As always, your hard work is greatly appreciated. I apologize for my poor English. I'm using DeepL, so it may not be the best translation).

**Comment by onechu** [comment]
background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

Other than the logs above, there was nothing else.
