### ISSUE TITLE
music.youtube.com connector doesn't work for a few days

### ISSUE THREAD

**Issue by NorthernBlow** [web-scrobbler/web-scrobbler#4613]
**Describe the bug**
music yotube connector works fine until last three days and after upgradee broken

**Environment**
-   OS: Arch Linux
-   Browser: Firefox
-   Extension version: Latest

**Comment by flavioislima** [comment]
I can confirm it doesn't work for me as well for both Linux (Arch and OpenSuse) on Firefox and Vivaldi.
But also doesn't work on Windows as well for same browsers:


Music is playing but still cannot recognize it:
![image](https://github.com/web-scrobbler/web-scrobbler/assets/26871415/575a7403-a132-4256-bb03-2c4c52a5d201)

Tried restarting the browser, reinstalling the extension, logging out and in again from Last.Fm and still nothing works.

**Comment by Kellen-wq** [comment]
for me it works, but adds comma after almost every artist name
![image](https://github.com/web-scrobbler/web-scrobbler/assets/76692731/23d8aa4a-1487-438a-9ba7-f3653814fef9)

**Comment by TheColorman** [comment]
Probably related to #4587. Works fine for me on Windows/Google Chrome + Chrome desktop PWA. The rework made the connector use the javascript api for playing media, is your browser correctly detecting the music?

**Comment by zbigniewzolnierowicz** [comment]
Can confirm the same error on macOS + Firefox.

**Comment by vpzomtrrfrt** [comment]
I see information in `navigator.mediaSession.metadata` while playing so it does seem to exist

**Comment by NorthernBlow** [comment]
on Windows 10 + Firefox same problem, Windows 11 + Firefox same

**Comment by CECTPAyTkyHECu** [comment]
Have the same problem too on Windows 11 and Firefox

**Comment by abrown19** [comment]
Oddly enough, this is working fine for me in Microsoft Edge only (Windows 10 and Windows 11) using the plugin version from the Edge Add-ons site. The other browsers I've tested (firefox, chrome, vivaldi) using the Mozilla or Chrome Web Store versions are reporting errors.

**Comment by TheColorman** [comment]
Maybe related, but I get a "The track is not recognized" notification for every song, but it detects just fine.

**Comment by 1shira** [comment]
I did some testing an discovered, that the `navigator` Object that the extension accesses is not the same that the page accesses in Firefox. 

I tried setting the `navigator.mediaSession` myself to debug, however when setting it and then reading it again to get the track, the extention show's what I have set, while the browser console still shows the song currently playing. 
Even after removing the code that sets the `mediaSession`, it stayed as what I had set while the console on the page always showed the currently playing song.

It seems the extention gets it's own `navigator` Object from Firefox and cannot access the navigator the page uses, causeing the extention to be unable to detect anything on Firefox with the current implementation.

I suggest using selector classes like before #4587 since the version before still works

**Comment by jaccarmac** [comment]
Did we ever look for documentation about `navigator` behavior or bugs in Firefox? I'm very confused by this issue and the complexity it adds to our use of `mediaSession`.

> I tried setting the navigator.mediaSession myself to debug

This sets off a few alarm bells since MDN notes that the object is read-only.

**Comment by rob9315** [comment]
I ran into that a lot on different sites and was generally very confused.

**Comment by jaccarmac** [comment]
While the behavior in the debugger in console is confusing, I can't duplicate the issue and can access `navigator.mediaSession.metadata` from Firefox. Unless there's an issue peculiar to Firefox, we can roll back to the simpler code there.

**Comment by rob9315** [comment]
this is an old issue, youtube-music now does dom injection and so will have access to the mediaSession
https://github.com/web-scrobbler/web-scrobbler/commit/823ead6e24dc4f93ede9832212b81477d7267cb6
