### ISSUE TITLE
Tracks titles edited despite no regex/bulk edits on YouTube Music

### ISSUE THREAD

**Issue by Alespren** [web-scrobbler/web-scrobbler#4991]
**Describe the bug**
When scrobbling Charli XCX's music on YouTube Music, tracks that feature other artists are being edited to remove the featured artist. For example "Guess (feat. Billie Eilish)" is scrobbled as "Guess". I have no regex/bulk filters, and no edited tracks. This is a problem because Guess and Guess (feat. Billie Eilish) are distinctly different songs and there's no way to distinguish that if the full title isn't scrobbled.

**How to reproduce**
1. Play "Guess (feat. Billie Eilish)" or any other song on the brat remix album on YouTube Music
2. Check what is scrobbled

**Expected behavior**
The track should be scrobbled as "Guess (feat. Billie Eilish)", which is what the track is titled on YouTube Music.

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Windows 11
-   Browser: Arc Browser
-   Extension version: v3.10.0

**Additional context**

**Comment by jaccarmac** [comment]
Do you have the "Use Youtube Music to get track info" option enabled or disabled? It's on the main page of options.

**Comment by Alespren** [comment]
I've tested it with the option enabled and disabled, with no change in behavior.

**Comment by jaccarmac** [comment]
Thanks for checking that. I can duplicate the behavior in Chrome, though it was a little hard to pull up the non-MV version of the song. At first blush the problem seems to be in the media state information coming from Chrome. If you visit the song on plain old YouTube do you also get a bad scrobble? https://www.youtube.com/watch?v=Q4d7SV9LYz4 for me results in "Guess feat. billie eilish (feat. Billie Eilish)"

**Comment by jaccarmac** [comment]
I can confirm in incognito Chrome (that is, no extension) that the `mediaSession` is the problem. So while I understand this is a problem with the track, it is technically the expected behavior. That object usually provides better information than the DOM and I don't see a way to detect that the behavior should change here. If you edit the scrobbling information, the extension should save it for the video.

![image](https://github.com/user-attachments/assets/5c04ca59-d258-4b1a-aa13-2cd74d96532b)
