### ISSUE TITLE
Easier definition of custom matches against connectors

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#526]
Adding custom rules is somewhat convoluted having to drill down into the options page and select the connector and add the custom rule in here. 

I propose the following kind of approach that I have seen some proxy extensions have where you can click on an icon in the browser and add a custom rule from here. 

![2015-01-12 13_38_14-easier definition of custom matches against connectors issue 526 david-saba](https://cloud.githubusercontent.com/assets/713525/5702980/46090642-9a60-11e4-9792-fc42a5e2476f.png)

Use cases I can see are adding rules for Bandcamp artist pages which are hosted on their own domain. 
- http://music.rusuden.com/album/acid-abyss-vol-1

Related to #334

**Comment by david-sabata** [comment]
Sounds good. Simply clicking the icon and saying "scrobble this web with that connector" would be nice.
The only thing would be the need to show the icon in address bar all the time, for every website. And frankly I don't like that much, because it stops being and page action (shows up for relevant pages) and becomes browser action (always visible in toolbar).

Is adding a new site really so much repeated task?

**Comment by inverse** [comment]
The only place I personally would use it would be for Bandcamp premium artists with custom domains. Which I guess isn't too hard to add a new pattern just thought it might be a nice addition to facilitate to ease of such things.  

I guess the drawback of this would be that users might be tempted to try and use it to assign scrobblers not meant for certain pages to associated with a scrobbler.  

It was only an idea which I might try and play around with and wanted to get some feedback on.

**Comment by marsjaninzmarsa** [comment]
I'll more likely see context menu item than browser action (as Firefox user).
